### ISSUE TITLE
Add a preloader  

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-daffodil#13]
Add any amazing page pre loader. Please attach the screenshot.

Happy coding 😁

**Comment by KJCastillo** [comment]
Can I give this a shot?

**Comment by Aniket762** [comment]
Sure man go for it 💪

**Comment by KJCastillo** [comment]
thanks!

**Comment by rahulvermafreelancer** [comment]
Hey, can i add some amazing preloader in your website?

**Comment by Aniket762** [comment]
@rahulvermafreelancer it will be great if you share the screenshot of the pre loader you are talking about
