### ISSUE TITLE
Add subject names and corresponding  picture

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-daffodil#19]
Include all the subjects for both electrical and electronics semesters

**Comment by SayantanMaiti** [comment]
I am Interested !

**Comment by Aniket762** [comment]
@SayantanMaiti go for it 😁

Attach screenshots of the changes you made

**Comment by SayantanMaiti** [comment]
![electricalsem](https://user-images.githubusercontent.com/68146055/95469755-9fc5fc00-099d-11eb-9247-438771ab4263.jpg)

![electronicssem](https://user-images.githubusercontent.com/68146055/95469828-b10f0880-099d-11eb-8389-6efdedf35a09.jpg)

added subjects
designed the buttons
added margin-left to h2 tag

**Comment by prachi0513** [comment]
can I work on this repo and is its pr adding to hacktoberfest 2020 as am a newbie in this fest

**Comment by Aniket762** [comment]
Hey @prachi0513 , good to know that you are interested and yes this PR will be added to hacktoberfest 2020.

Here already @SayantanMaiti has added the name of the subjects. If you want to contribute in this repo you can add picture for each and every subject and style them accordingly.

Please attach the screenshot of the changes you made.

Happy Coding 😀

**Comment by prachi0513** [comment]
okie sure : ) i'll do this .

**Comment by Bhairavi-shah** [comment]
Is there something I can help with if @prachi0513 has not finished yet?

**Comment by Aniket762** [comment]
Hey @prachi0513  are you on it?

**Comment by saumyasingh203** [comment]
Hello! Can I contribute to this repo please?  :)

**Comment by Aniket762** [comment]
Hey @saumyasingh203, go for it . The name of the subjects are added choose corresponding picture and give it a card look. Don't forget to share the screenshot while you create PR.

Happy Coding 😀

**Comment by saumyasingh203** [comment]
@Aniket762  okay, on it :)

**Comment by saumyasingh203** [comment]
The subjects haven't been added in the main repository it seems

**Comment by saumyasingh203** [comment]
Also, where do I have to choose the pictures from?

**Comment by Aniket762** [comment]
@saumyasingh203 on you

**Comment by Aniket762** [comment]
> The subjects haven't been added in the main repository it seems

Yes I know . These are the subjects select corresponding picture give it a card look. And then I will merge

**Comment by saumyasingh203** [comment]
![image](https://user-images.githubusercontent.com/59359575/95991503-7815de80-0e4a-11eb-9c87-6a0807c42b4d.png)
![image](https://user-images.githubusercontent.com/59359575/95991523-7ea45600-0e4a-11eb-9415-683c95c190f9.png)

@Aniket762 
How does it look?

**Comment by Aniket762** [comment]
Hey @saumyasingh203 looks great 🤩 it will be great if you can add box shadow for every card and create a PR. Did you do it for electronics sem as well?

**Comment by saumyasingh203** [comment]
Okay I will add shadows too💯   
For electronics, not yet, shall I add the subjects by myself in electronics or do you have a list ?

**Comment by saumyasingh203** [comment]
Or do I have to copy the same list as of now?

**Comment by saumyasingh203** [comment]
![image](https://user-images.githubusercontent.com/59359575/96005636-41e05b00-0e5a-11eb-9b69-df6efe95d492.png)

I have added the same set of subjects for both currently

**Comment by saumyasingh203** [comment]
![Uploading image.png…]()

**Comment by Aniket762** [comment]
@SayantanMaiti please add the subjects for electronics sem

**Comment by Aniket762** [comment]
@saumyasingh203 great work 😍

**Comment by Aniket762** [comment]
> ![image](https://user-images.githubusercontent.com/59359575/95991503-7815de80-0e4a-11eb-9c87-6a0807c42b4d.png)
> ![image](https://user-images.githubusercontent.com/59359575/95991523-7ea45600-0e4a-11eb-9415-683c95c190f9.png)
> 
> @Aniket762
> How does it look?

Hey @saumyasingh203 can you create a PR with the changes you made! I will add the subjects for electronics sem. Thanks for contributing

**Comment by SayantanMaiti** [comment]
![electronics](https://user-images.githubusercontent.com/68146055/96104810-e7490c80-0ef6-11eb-83d5-d68a8ad9575a.jpg)
electronic subjects added

**Comment by saumyasingh203** [comment]
@Aniket762 
I have to change the names of the subjects right?

**Comment by Aniket762** [comment]
> @Aniket762
> I have to change the names of the subjects right?

You need to add. In 1st semester the students are divided into two halves electrical and electronics. And correspondingly have certain subjects associated. The way you added cover photos for electrical sem subjects in a similar way add for electronics sem.

I hope it's clear  😄

**Comment by saumyasingh203** [comment]
Yes it's clear!  I'm on it  👍

**Comment by saumyasingh203** [comment]
![image](https://user-images.githubusercontent.com/59359575/96121853-3ea6a700-0f0e-11eb-8c4d-28aa2979c204.png)
![image](https://user-images.githubusercontent.com/59359575/96121877-49f9d280-0f0e-11eb-824a-c8e048706bb0.png)

I have added accordingly in electronics!  
:)
