### ISSUE TITLE
Add 2 more pages to the website.

### ISSUE THREAD

**Issue by sayna3311** [Webwiznitr/Project-daffodil#32]
Add 2 separate pages for Electronics and Electrical sem with the same layout as given on the homepage.

**Comment by IBTechRaj** [comment]
I am trying to contribute to some open-source projects. I am not sure whether this is one.  This is not assigned yet. Is it because there were none who volunteered to contribute, or the contributors were not accepted?  Since I am a beginner, I am not sure. I need more information. Thanks
