### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by Aniket762** [Webwiznitr/Project-daffodil#6]
Add a toggle button in navbar which changes the mode from light to dark.

Attach the Screenshots of the changes you made

**Comment by KatySage** [comment]
could I try to tackle this, please?

**Comment by Aniket762** [comment]
Hey @KatySage, go for it

Happy coding 😁

**Comment by KatySage** [comment]
![Screen Shot 2020-10-06 at 4 34 40 PM](https://user-images.githubusercontent.com/68826585/95259220-dc0a2880-07f4-11eb-83f8-50c77d3275e8.png)
![Screen Shot 2020-10-06 at 4 34 31 PM](https://user-images.githubusercontent.com/68826585/95259226-df051900-07f4-11eb-9b85-95178f5045cc.png)
![Screen Shot 2020-10-06 at 4 34 16 PM](https://user-images.githubusercontent.com/68826585/95259229-e0cedc80-07f4-11eb-9cb1-b5445fa3792b.png)
![Screen Shot 2020-10-06 at 4 34 52 PM](https://user-images.githubusercontent.com/68826585/95259236-e4626380-07f4-11eb-8657-e29db312212e.png)

I changed the footer to a png to make it transparent, but I'm not a GIMP wizard, so it's a little rough around the edges. I put the working GIMP file (.xcf) in the images folder if you or someone else is better at that. 

Other than that, let me know of any problems you spot! I didn't want to change the hero image's brightness, but I could do that if you'd like.
